### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Blanca-estela-valerio-rivero#1]
Infografía-Blanca Estela
[Conceptos y Funciones de una Libreria.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Blanca-estela-valerio-rivero/files/14565498/Conceptos.y.Funciones.de.una.Libreria.pdf)

**Comment by ErikCuevas03** [comment]
De acuerdo la rubrica la calificación es de 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
